stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  image:
    name: klakegg/hugo:0.82.0-alpine
    entrypoint: ["/bin/sh", "-c"]
  stage: build
  script:
    - hugo --minify
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  image:
    name: williamjackson/netlify-cli:3.13.5
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build
  only:
    - master
